// Generated from the Admin API 2026-07 by scripts/generate-metafield-types.ts. Do not edit.
// Run `npm run generate:metafield-types` to refresh it.

export interface MetafieldTypeInfo {
  readonly category: string;
  // Whether values that predate a definition can be adopted into one of this type. It is not
  // a statement about retyping a definition that already exists, which Shopify never allows.
  readonly migratable: boolean;
  readonly validations: readonly string[];
}

export const METAFIELD_TYPES = {
  antenna_gain: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  area: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  article_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  battery_charge_capacity: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  battery_energy_capacity: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  boolean: { category: 'TRUE_FALSE', migratable: true, validations: [] },
  capacitance: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  collection_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  color: { category: 'COLOR', migratable: true, validations: [] },
  company_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  concentration: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  customer_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  data_storage_capacity: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  data_transfer_rate: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  date: { category: 'DATE_TIME', migratable: true, validations: ['max', 'min'] },
  date_time: { category: 'DATE_TIME', migratable: true, validations: ['max', 'min'] },
  dimension: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  disclosure_reference: { category: 'REFERENCE', migratable: true, validations: ['metaobject_definition_ids', 'metaobject_definition_types'] },
  display_density: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  distance: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  duration: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  electric_current: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  electrical_resistance: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  energy: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  file_reference: { category: 'REFERENCE', migratable: true, validations: ['file_type_options'] },
  frequency: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  id: { category: 'ID', migratable: true, validations: ['max', 'min', 'regex'] },
  illuminance: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  inductance: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  json: { category: 'JSON', migratable: true, validations: ['schema'] },
  jurisdiction: { category: 'TEXT', migratable: true, validations: [] },
  language: { category: 'LANGUAGE', migratable: true, validations: [] },
  link: { category: 'LINK', migratable: true, validations: ['allowed_domains'] },
  'list.antenna_gain': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.area': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.article_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.battery_charge_capacity': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.battery_energy_capacity': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.capacitance': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.collection_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.color': { category: 'COLOR', migratable: true, validations: ['list.max', 'list.min'] },
  'list.company_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.concentration': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.customer_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.data_storage_capacity': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.data_transfer_rate': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.date': { category: 'DATE_TIME', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.date_time': { category: 'DATE_TIME', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.dimension': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.disclosure_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min', 'metaobject_definition_ids', 'metaobject_definition_types'] },
  'list.display_density': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.distance': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.duration': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.electric_current': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.electrical_resistance': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.energy': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.file_reference': { category: 'REFERENCE', migratable: true, validations: ['file_type_options', 'list.max', 'list.min'] },
  'list.frequency': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.illuminance': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.inductance': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.jurisdiction': { category: 'TEXT', migratable: true, validations: ['list.max', 'list.min'] },
  'list.link': { category: 'LINK', migratable: true, validations: ['allowed_domains', 'list.max', 'list.min'] },
  'list.luminous_flux': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.mass_flow_rate': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.metaobject_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min', 'metaobject_definition_id', 'metaobject_definition_type'] },
  'list.mixed_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min', 'metaobject_definition_ids', 'metaobject_definition_types'] },
  'list.number_decimal': { category: 'NUMBER', migratable: true, validations: ['list.max', 'list.min', 'max', 'max_precision', 'min'] },
  'list.number_integer': { category: 'NUMBER', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.order_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.page_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.power': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.pressure': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.product_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.product_taxonomy_value_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min', 'product_taxonomy_attribute_handle'] },
  'list.rating': { category: 'RATING', migratable: true, validations: ['list.max', 'list.min', 'scale_max', 'scale_min'] },
  'list.resolution': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.rotational_speed': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.single_line_text_field': { category: 'TEXT', migratable: true, validations: ['choices', 'list.max', 'list.min', 'max', 'min', 'regex'] },
  'list.sound_level': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.speed': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.temperature': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.thermal_power': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.url': { category: 'URL', migratable: true, validations: ['allowed_domains', 'list.max', 'list.min'] },
  'list.variant_reference': { category: 'REFERENCE', migratable: true, validations: ['list.max', 'list.min'] },
  'list.voltage': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.volume': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.volumetric_flow_rate': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  'list.weight': { category: 'MEASUREMENT', migratable: true, validations: ['list.max', 'list.min', 'max', 'min'] },
  luminous_flux: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  mass_flow_rate: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  metaobject_reference: { category: 'REFERENCE', migratable: true, validations: ['metaobject_definition_id', 'metaobject_definition_type'] },
  mixed_reference: { category: 'REFERENCE', migratable: true, validations: ['metaobject_definition_ids', 'metaobject_definition_types'] },
  money: { category: 'MONEY', migratable: true, validations: [] },
  multi_line_text_field: { category: 'TEXT', migratable: true, validations: ['max', 'min', 'regex'] },
  number_decimal: { category: 'NUMBER', migratable: true, validations: ['max', 'max_precision', 'min'] },
  number_integer: { category: 'NUMBER', migratable: true, validations: ['max', 'min'] },
  order_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  page_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  power: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  pressure: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  product_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  product_taxonomy_disclosure_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  product_taxonomy_value_reference: { category: 'REFERENCE', migratable: true, validations: ['product_taxonomy_attribute_handle'] },
  rating: { category: 'RATING', migratable: true, validations: ['scale_max', 'scale_min'] },
  resolution: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  rich_text_field: { category: 'TEXT', migratable: true, validations: [] },
  rotational_speed: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  single_line_text_field: { category: 'TEXT', migratable: true, validations: ['choices', 'max', 'min', 'regex'] },
  sound_level: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  speed: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  temperature: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  thermal_power: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  url: { category: 'URL', migratable: true, validations: ['allowed_domains'] },
  variant_reference: { category: 'REFERENCE', migratable: true, validations: [] },
  voltage: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  volume: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  volumetric_flow_rate: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
  weight: { category: 'MEASUREMENT', migratable: true, validations: ['max', 'min'] },
} as const satisfies Record<string, MetafieldTypeInfo>;

export type MetafieldTypeName = keyof typeof METAFIELD_TYPES;

export const METAFIELD_OWNER_TYPES = [
  'API_PERMISSION',
  'ARTICLE',
  'BLOG',
  'CARTTRANSFORM',
  'COLLECTION',
  'COMPANY',
  'COMPANY_LOCATION',
  'CUSTOMER',
  'DELIVERY_CUSTOMIZATION',
  'DISCOUNT',
  'DRAFTORDER',
  'FULFILLMENT_CONSTRAINT_RULE',
  'GIFT_CARD_TRANSACTION',
  'LOCATION',
  'MARKET',
  'ORDER',
  'ORDER_ROUTING_LOCATION_RULE',
  'PAGE',
  'PAYMENT_CUSTOMIZATION',
  'PRODUCT',
  'PRODUCTVARIANT',
  'SELLING_PLAN',
  'SHOP',
  'TRANSFER',
  'VALIDATION',
] as const;

export type MetafieldOwnerType = typeof METAFIELD_OWNER_TYPES[number];
